name = "Vermishell"
author = "Mykhailo Dvali"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af2e6c82cf71cb6b30837780bfcadcf56bd59e8861cae7cfb89d90919e126af7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
