name = "Pasta"
author = "Mykhailo Dvali"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c95030d5166c23d3aea00adc4bd48ed5b0b1cd4825d07b18f93377cfd4e7be6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
